### ISSUE TITLE
Can't clone submodules

### ISSUE THREAD

**Issue by BowlOfSoup** [richbl/old-files-delete#2] opened 2022-09-02 14:29 UTC
When trying to clone the repo I get the following error(s). How can I prevent this?
When I don't use `--recursive` it does not give any errors (but then the script doesn't work obviously).

Cloning into 'old-files-delete'...
remote: Enumerating objects: 65, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 65 (delta 8), reused 15 (delta 7), pack-reused 45
Unpacking objects: 100% (65/65), done.
Submodule 'bash-lib' (git@github.com:richbl/bash-lib.git) registered for path 'bash-lib'
Cloning into '/home/administrator/old-files-delete/bash-lib'...
The authenticity of host 'github.com (140.82.121.3)' can't be established.
ECDSA key fingerprint is SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,140.82.121.3' (ECDSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:richbl/bash-lib.git' into submodule path '/home/administrator/old-files-delete/bash-lib' failed
Failed to clone 'bash-lib'. Retry scheduled
Cloning into '/home/administrator/old-files-delete/bash-lib'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by richbl** [comment] 2022-09-02 21:40
@BowlOfSoup, very strange. It seems as if there's some kind of permissions issue here, but I'm unable to repro the issue. I just did a clean clone --recursive, and had expected results:

```
Cloning into 'old-files-delete'...
remote: Enumerating objects: 65, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 65 (delta 8), reused 15 (delta 7), pack-reused 45
Receiving objects: 100% (65/65), 28.67 KiB | 402.00 KiB/s, done.
Resolving deltas: 100% (28/28), done.
Submodule 'bash-lib' (git@github.com:richbl/bash-lib.git) registered for path 'bash-lib'
Cloning into '/home/richbl/Documents/dev/old-files-delete/bash-lib'...
remote: Enumerating objects: 54, done.        
remote: Counting objects: 100% (10/10), done.        
remote: Compressing objects: 100% (8/8), done.        
remote: Total 54 (delta 2), reused 6 (delta 2), pack-reused 44        
Receiving objects: 100% (54/54), 28.59 KiB | 2.04 MiB/s, done.
Resolving deltas: 100% (16/16), done.
```
I'll continue to investigate, but in the meantime, the workaround is to clone the base project (this project, `old-files-delete`) without the `--recursive` switch, then `cd` into the newly created project directory and separately clone the submodule project (`bash-lib`). The result will be the same: the `bash-lib` folder should now be populated with the appropriate submodule project files available to the `old-files-delete` parent project.

I suspect some changes have occurred with the permissions handling of Git submodules on Github. More to come.

**Comment by richbl** [comment] 2022-09-02 22:01
@BowlOfSoup, did a bit of research and the quickest solution was to update the project `.gitmodule` file to use http instead of ssh (default). I've updated this file appropriately. **Please confirm that this works for your use case.** 

In the meantime, I'll investigate a more appropriate solution of syncing public keys between git projects and submodules.

Thanks

**Comment by richbl** [comment] 2022-09-04 01:08
To follow up, here's a good explanation of how Github manages Git submodules formatting, particularly as it relates to its use of SSH by default over HTTPS. https://github.com/orgs/community/discussions/21659

So, in short, using SSH with Github and submodules should always work, provided that you have a valid Github SSH key. Otherwise, using HTTPS (which usually just works) can potentially cause issues if the related `.gitmodules` file is not also configured to use HTTPS.

In my quick configuration tests, it appears that reconfiguring a SSH-configured `.gitmodules` files to use HTTPS works with both HTTPS and SSH use cases. And so, hence the change made here to update that file appropriately to use HTTPS.

@BowlOfSoup, I'll wait until I hear back from you before closing this issue. If I don't get a response in the next week, I'll assume the issue is appropriately resolved. 

Thanks for identifying and reporting this unusual Git/Github issue.

**Closed** 2022-09-12 22:15 UTC

**Comment by BowlOfSoup** [comment] 2022-09-20 08:27
Thanks! It works for me now 👍
